---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Depends on
  work-vpc.yml,
  work-securitygroup.yml,
  work-iamrole.yml,
  work-zabbix-server.yml,
  work-route53.yml

Parameters:
  PJName:
    Description: Name of this project
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: MyPJ

  EC2AMI:
    Description: Amazon Linux 2 Latest AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  KeyName: 
    Description: Select your key pair.
    Type: AWS::EC2::KeyPair::KeyName

  # Used to store Fluentd config files
  S3Name:
    Description: >-
      Name of the S3 bucket to use for workspace.
      Required files must be stored.
    Type: String
    Default: cfn-workspace-2021****


Resources:
  FluentdServer:
    Type: AWS::EC2::Instance
    Properties: 
      BlockDeviceMappings: 
        - DeviceName: /dev/xvda
          Ebs: 
            VolumeSize: 8
            VolumeType: gp2
            DeleteOnTermination: true
      ImageId: !Ref EC2AMI
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref FluentdServerInstanceProfile
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          GroupSet: 
            - Fn::ImportValue: !Sub ${PJName}-SgFluentdServer
            - Fn::ImportValue: !Sub ${PJName}-SgZabbixAgent
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue: !Sub ${PJName}-PublicSubnet1
      Tags: 
        - Key: Name
          Value: !Sub ${PJName}-FluentdServer
      UserData: 
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            yum -y update
            timedatectl set-timezone Asia/Tokyo
            curl -L https://toolbelt.treasuredata.com/sh/install-amazon2-td-agent3.sh | sh
            mkdir -p /var/log/firelens/nginx
            chown -R td-agent:td-agent /var/log/firelens/
            aws s3 cp s3://${S3Name}/td-agent.conf /etc/td-agent/td-agent.conf
            yum install -y https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
            yum install -y zabbix-agent2
            sed -i -e "s/^Server=127.0.0.1/Server=${ZabbixDomain}/g" /etc/zabbix/zabbix_agent2.conf
            sed -i -e "s/^ServerActive=127.0.0.1/ServerActive=${ZabbixDomain}/g" /etc/zabbix/zabbix_agent2.conf
            sed -i -e "s/^Hostname=Zabbix server/Hostname=Fluentd server/g" /etc/zabbix/zabbix_agent2.conf
            systemctl start td-agent zabbix-agent2
            systemctl enable td-agent zabbix-agent2
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource FluentdServer --region ${AWS::Region}
          - {
              ZabbixDomain: !ImportValue ZabbixServerDNSName
            }
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT5M

  FluentdServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Fn::ImportValue: !Sub ${PJName}-S3AccessRole

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Sub ${PJName}-PrivateHostedZoneID
      Name: !Sub
        - fluentd.${Domain}
        - { Domain: !ImportValue HostedZoneName }
      Type: A
      TTL: 300
      ResourceRecords:
        - !GetAtt FluentdServer.PrivateIp


Outputs:
  FluentdServerDNSName:
    Description: Fluentd Server Private DNS Name
    Value: !Ref DNSRecord
    Export:
      Name: FluentdServerDNSName